N = 40

BALL_SIZE = 16
MU = 10
NUMBER_OF_BINS = int(N/MU)
BIN_SIZE = 2*MU
BIN_SIZE_IN_BYTES = BIN_SIZE*BALL_SIZE
EPSILON = 1/4

LOCAL_MEMORY_SIZE = BIN_SIZE_IN_BYTES

DATA_LOCATION = 'data.txt'
BINS_LOCATION = 'bins.txt'
OVERFLOW_LOCATION = 'overflow.txt'